# Generated by Django 5.0 on 2024-03-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gcpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('stomach_tissue_type', models.CharField(blank=True, max_length=100, null=True)),
                ('part_of_stomach', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_patients', models.CharField(blank=True, max_length=100, null=True)),
                ('cohorts', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_method', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_sample_size', models.CharField(blank=True, max_length=100, null=True)),
                ('control', models.CharField(blank=True, max_length=100, null=True)),
                ('fold_change', models.CharField(blank=True, max_length=100, null=True)),
                ('over_expression', models.CharField(blank=True, max_length=10, null=True)),
                ('down_expression', models.CharField(blank=True, max_length=10, null=True)),
                ('subtype_of_cancer', models.CharField(blank=True, max_length=100, null=True)),
                ('cancer_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment_given', models.CharField(blank=True, max_length=100, null=True)),
                ('chemotherapy_drug_regimen', models.CharField(blank=True, max_length=100, null=True)),
                ('mass_spec_platforms', models.CharField(blank=True, max_length=50, null=True)),
                ('mass_spec_acquisition', models.CharField(blank=True, max_length=50, null=True)),
                ('search_engine', models.CharField(blank=True, max_length=50, null=True)),
                ('bacterial_viral_infection', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('remark_on_expression', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneSymbol',
            fields=[
                ('gene_symbol', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('type_of_marker', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pmid',
            fields=[
                ('pmid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenesymbolGcpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcpdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genesymbol_gcpdb_gcpdb', to='gcpdb.gcpdb')),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genesymbol_gcpdb_gs', to='gcpdb.genesymbol')),
            ],
            options={
                'unique_together': {('gene_symbol', 'gcpdb')},
            },
        ),
        migrations.AddField(
            model_name='gcpdb',
            name='gene_symbol',
            field=models.ManyToManyField(related_name='genesymbol_gcpdb', through='gcpdb.GenesymbolGcpdb', to='gcpdb.genesymbol'),
        ),
        migrations.CreateModel(
            name='PmidGcpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcpdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pmid_gcpdb_gc', to='gcpdb.gcpdb')),
                ('pmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pmid_gcpdb_pm', to='gcpdb.pmid')),
            ],
            options={
                'unique_together': {('pmid', 'gcpdb')},
            },
        ),
        migrations.AddField(
            model_name='gcpdb',
            name='pmid',
            field=models.ManyToManyField(related_name='pmid_gcpdb', through='gcpdb.PmidGcpdb', to='gcpdb.pmid'),
        ),
        migrations.CreateModel(
            name='PmidMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmid_marker_pm', to='gcpdb.pmid')),
                ('type_of_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmid_marker_tm', to='gcpdb.marker')),
            ],
            options={
                'unique_together': {('pmid', 'type_of_marker')},
            },
        ),
        migrations.AddField(
            model_name='pmid',
            name='marker',
            field=models.ManyToManyField(related_name='pmid_marker', through='gcpdb.PmidMarker', to='gcpdb.marker'),
        ),
        migrations.CreateModel(
            name='Refseq',
            fields=[
                ('refseq', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refseq_genesymbol', to='gcpdb.genesymbol')),
            ],
        ),
        migrations.CreateModel(
            name='RefseqGcpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcpdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refseq_gcpdb_gcpdb', to='gcpdb.gcpdb')),
                ('refseq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refseq_gcpdb_ref', to='gcpdb.refseq')),
            ],
            options={
                'unique_together': {('refseq', 'gcpdb')},
            },
        ),
        migrations.AddField(
            model_name='gcpdb',
            name='refseq',
            field=models.ManyToManyField(related_name='refseq_gcpdb', through='gcpdb.RefseqGcpdb', to='gcpdb.refseq'),
        ),
        migrations.CreateModel(
            name='Uniprot',
            fields=[
                ('uniprot_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('gene_symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uniprot_genesymbol', to='gcpdb.genesymbol')),
            ],
        ),
        migrations.CreateModel(
            name='UniprotGcpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcpdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniprot_gcpdb_uni_gcpdb', to='gcpdb.gcpdb')),
                ('uniprot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniprot_gcpdb_uni', to='gcpdb.uniprot')),
            ],
            options={
                'unique_together': {('uniprot', 'gcpdb')},
            },
        ),
        migrations.AddField(
            model_name='gcpdb',
            name='uniprot',
            field=models.ManyToManyField(related_name='uniprot_gcpdb', through='gcpdb.UniprotGcpdb', to='gcpdb.uniprot'),
        ),
    ]
